import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { Providers } from "./providers";
import { auth } from "@/auth";
import { Footer } from "@/components/footer";
import { Open_Sans } from 'next/font/google'
import { Toaster } from "@/components/ui/toaster"
 
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const openSans = Open_Sans({
  subsets: ['latin'],
  display: 'swap',
})
 

export const metadata: Metadata = {
  title: "Cooperativa de ahorro ANEUPI",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await auth()
  return (
    <html lang="en">
      <body
        className={`${openSans.className}`}
      >
        <Providers>
          
          <Navbar session={session} />
          
          <div className="min-h-screen">
          {children}
          </div>
          <Footer />
          <Toaster />

        </Providers>
      </body>
    </html>
  );
}
